<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Fluentd</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fluentd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.tag.fluentd</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.fluentd</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fluentd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;)(\w+)(\s([^&gt;]+?))?(&gt;)</string>
			<key>name</key>
			<string>entity.tag.start.fluentd</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fluentd</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.tag.fluentd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.fluentd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;/)(\w+)(&gt;)</string>
			<key>name</key>
			<string>entity.tag.end.fluentd</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive.fluentd</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.fluentd</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((\w+) ([^\n#]+))</string>
			<key>name</key>
			<string>keyword.directive.generic.fluentd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fluentd</string>
	<key>uuid</key>
	<string>441704c1-2d2c-40b8-a251-5b811ea19fdf</string>
</dict>
</plist>
